markov = require("./markov")
escapeRegExp = (string) ->
  string.replace()

# When henry whines go to https://static-cdn.jtvnw.net/emoticons
twitchEmoticons =
  "4Head" : "https://static-cdn.jtvnw.net/emoticons/v1/354/1.0"
  "ANELE" : "https://static-cdn.jtvnw.net/emoticons/v1/3792/1.0"
  "ArgieB8" : "https://static-cdn.jtvnw.net/emoticons/v1/51838/1.0"
  "ArsonNoSexy" : "https://static-cdn.jtvnw.net/emoticons/v1/50/1.0"
  "AsianGlow" : "https://static-cdn.jtvnw.net/emoticons/v1/74/1.0"
  "AthenaPMS" : "https://static-cdn.jtvnw.net/emoticons/v1/32035/1.0"
  "BabyRage" : "https://static-cdn.jtvnw.net/emoticons/v1/22639/1.0"
  "BatChest" : "https://static-cdn.jtvnw.net/emoticons/v1/1905/1.0"
  "BCouch" : "https://static-cdn.jtvnw.net/emoticons/v1/83536/1.0"
  "BCWarrior" : "https://static-cdn.jtvnw.net/emoticons/v1/30/1.0"
  "BibleThump" : "https://static-cdn.jtvnw.net/emoticons/v1/86/1.0"
  "BigBrother" : "https://static-cdn.jtvnw.net/emoticons/v1/1904/1.0"
  "BionicBunion" : "https://static-cdn.jtvnw.net/emoticons/v1/24/1.0"
  "BlargNaut" : "https://static-cdn.jtvnw.net/emoticons/v1/38/1.0"
  "bleedPurple" : "https://static-cdn.jtvnw.net/emoticons/v1/62835/1.0"
  "BloodTrail" : "https://static-cdn.jtvnw.net/emoticons/v1/69/1.0"
  "BORT" : "https://static-cdn.jtvnw.net/emoticons/v1/243/1.0"
  "BrainSlug" : "https://static-cdn.jtvnw.net/emoticons/v1/881/1.0"
  "BrokeBack" : "https://static-cdn.jtvnw.net/emoticons/v1/4057/1.0"
  "BuddhaBar" : "https://static-cdn.jtvnw.net/emoticons/v1/27602/1.0"
  "ChefFrank" : "https://static-cdn.jtvnw.net/emoticons/v1/90129/1.0"
  "cmonBruh" : "https://static-cdn.jtvnw.net/emoticons/v1/84608/1.0"
  "CoolCat" : "https://static-cdn.jtvnw.net/emoticons/v1/58127/1.0"
  "CorgiDerp" : "https://static-cdn.jtvnw.net/emoticons/v1/49106/1.0"
  "CougarHunt" : "https://static-cdn.jtvnw.net/emoticons/v1/21/1.0"
  "DAESuppy" : "https://static-cdn.jtvnw.net/emoticons/v1/973/1.0"
  "DansGame" : "https://static-cdn.jtvnw.net/emoticons/v1/33/1.0"
  "DatSheffy" : "https://static-cdn.jtvnw.net/emoticons/v1/170/1.0"
  "DBstyle" : "https://static-cdn.jtvnw.net/emoticons/v1/73/1.0"
  "deExcite" : "https://static-cdn.jtvnw.net/emoticons/v1/46249/1.0"
  "deIlluminati" : "https://static-cdn.jtvnw.net/emoticons/v1/46248/1.0"
  "DendiFace" : "https://static-cdn.jtvnw.net/emoticons/v1/58135/1.0"
  "DogFace" : "https://static-cdn.jtvnw.net/emoticons/v1/1903/1.0"
  "DOOMGuy" : "https://static-cdn.jtvnw.net/emoticons/v1/54089/1.0"
  "duDudu" : "https://static-cdn.jtvnw.net/emoticons/v1/62834/1.0"
  "EagleEye" : "https://static-cdn.jtvnw.net/emoticons/v1/20/1.0"
  "EleGiggle" : "https://static-cdn.jtvnw.net/emoticons/v1/4339/1.0"
  "FailFish" : "https://static-cdn.jtvnw.net/emoticons/v1/360/1.0"
  "FPSMarksman" : "https://static-cdn.jtvnw.net/emoticons/v1/42/1.0"
  "FrankerZ" : "https://static-cdn.jtvnw.net/emoticons/v1/65/1.0"
  "FreakinStinkin" : "https://static-cdn.jtvnw.net/emoticons/v1/39/1.0"
  "FUNgineer" : "https://static-cdn.jtvnw.net/emoticons/v1/244/1.0"
  "FunRun" : "https://static-cdn.jtvnw.net/emoticons/v1/48/1.0"
  "FuzzyOtterOO" : "https://static-cdn.jtvnw.net/emoticons/v1/168/1.0"
  "GingerPower" : "https://static-cdn.jtvnw.net/emoticons/v1/32/1.0"
  "GrammarKing" : "https://static-cdn.jtvnw.net/emoticons/v1/3632/1.0"
  "HassaanChop" : "https://static-cdn.jtvnw.net/emoticons/v1/20225/1.0"
  "HassanChop" : "https://static-cdn.jtvnw.net/emoticons/v1/68/1.0"
  "HeyGuys" : "https://static-cdn.jtvnw.net/emoticons/v1/30259/1.0"
  "HotPokket" : "https://static-cdn.jtvnw.net/emoticons/v1/357/1.0"
  "HumbleLife" : "https://static-cdn.jtvnw.net/emoticons/v1/46881/1.0"
  "ItsBoshyTime" : "https://static-cdn.jtvnw.net/emoticons/v1/169/1.0"
  "Jebaited" : "https://static-cdn.jtvnw.net/emoticons/v1/90/1.0"
  "JKanStyle" : "https://static-cdn.jtvnw.net/emoticons/v1/15/1.0"
  "JonCarnage" : "https://static-cdn.jtvnw.net/emoticons/v1/26/1.0"
  "KAPOW" : "https://static-cdn.jtvnw.net/emoticons/v1/9803/1.0"
  "Kappa" : "https://static-cdn.jtvnw.net/emoticons/v1/25/1.0"
  "KappaClaus" : "https://static-cdn.jtvnw.net/emoticons/v1/74510/1.0"
  "KappaPride" : "https://static-cdn.jtvnw.net/emoticons/v1/55338/1.0"
  "KappaRoss" : "https://static-cdn.jtvnw.net/emoticons/v1/70433/1.0"
  "KappaWealth" : "https://static-cdn.jtvnw.net/emoticons/v1/81997/1.0"
  "Keepo" : "https://static-cdn.jtvnw.net/emoticons/v1/1902/1.0"
  "KevinTurtle" : "https://static-cdn.jtvnw.net/emoticons/v1/40/1.0"
  "Kippa" : "https://static-cdn.jtvnw.net/emoticons/v1/1901/1.0"
  "Kreygasm" : "https://static-cdn.jtvnw.net/emoticons/v1/41/1.0"
  "Mau5" : "https://static-cdn.jtvnw.net/emoticons/v1/30134/1.0"
  "mcaT" : "https://static-cdn.jtvnw.net/emoticons/v1/35063/1.0"
  "MikeHogu" : "https://static-cdn.jtvnw.net/emoticons/v1/81636/1.0"
  "MingLee" : "https://static-cdn.jtvnw.net/emoticons/v1/68856/1.0"
  "MrDestructoid" : "https://static-cdn.jtvnw.net/emoticons/v1/28/1.0"
  "MVGame" : "https://static-cdn.jtvnw.net/emoticons/v1/29/1.0"
  "NinjaTroll" : "https://static-cdn.jtvnw.net/emoticons/v1/45/1.0"
  "NomNom" : "https://static-cdn.jtvnw.net/emoticons/v1/90075/1.0"
  "NoNoSpot" : "https://static-cdn.jtvnw.net/emoticons/v1/44/1.0"
  "NotATK" : "https://static-cdn.jtvnw.net/emoticons/v1/34875/1.0"
  "NotLikeThis" : "https://static-cdn.jtvnw.net/emoticons/v1/58765/1.0"
  "OhMyDog" : "https://static-cdn.jtvnw.net/emoticons/v1/81103/1.0"
  "OMGScoots" : "https://static-cdn.jtvnw.net/emoticons/v1/91/1.0"
  "OneHand" : "https://static-cdn.jtvnw.net/emoticons/v1/66/1.0"
  "OpieOP" : "https://static-cdn.jtvnw.net/emoticons/v1/356/1.0"
  "OptimizePrime" : "https://static-cdn.jtvnw.net/emoticons/v1/16/1.0"
  "OSfrog" : "https://static-cdn.jtvnw.net/emoticons/v1/81248/1.0"
  "OSkomodo" : "https://static-cdn.jtvnw.net/emoticons/v1/81273/1.0"
  "OSsloth" : "https://static-cdn.jtvnw.net/emoticons/v1/81249/1.0"
  "panicBasket" : "https://static-cdn.jtvnw.net/emoticons/v1/22998/1.0"
  "PanicVis" : "https://static-cdn.jtvnw.net/emoticons/v1/3668/1.0"
  "PartyTime" : "https://static-cdn.jtvnw.net/emoticons/v1/76171/1.0"
  "PazPazowitz" : "https://static-cdn.jtvnw.net/emoticons/v1/19/1.0"
  "PeoplesChamp" : "https://static-cdn.jtvnw.net/emoticons/v1/3412/1.0"
  "PermaSmug" : "https://static-cdn.jtvnw.net/emoticons/v1/27509/1.0"
  "PeteZaroll" : "https://static-cdn.jtvnw.net/emoticons/v1/81243/1.0"
  "PeteZarollTie" : "https://static-cdn.jtvnw.net/emoticons/v1/81244/1.0"
  "PicoMause" : "https://static-cdn.jtvnw.net/emoticons/v1/27/1.0"
  "PipeHype" : "https://static-cdn.jtvnw.net/emoticons/v1/4240/1.0"
  "PJSalt" : "https://static-cdn.jtvnw.net/emoticons/v1/36/1.0"
  "PMSTwin" : "https://static-cdn.jtvnw.net/emoticons/v1/92/1.0"
  "PogChamp" : "https://static-cdn.jtvnw.net/emoticons/v1/88/1.0"
  "Poooound" : "https://static-cdn.jtvnw.net/emoticons/v1/358/1.0"
  "PraiseIt" : "https://static-cdn.jtvnw.net/emoticons/v1/38586/1.0"
  "PRChase" : "https://static-cdn.jtvnw.net/emoticons/v1/28328/1.0"
  "PunchTrees" : "https://static-cdn.jtvnw.net/emoticons/v1/47/1.0"
  "PuppeyFace" : "https://static-cdn.jtvnw.net/emoticons/v1/58136/1.0"
  "RaccAttack" : "https://static-cdn.jtvnw.net/emoticons/v1/27679/1.0"
  "RalpherZ" : "https://static-cdn.jtvnw.net/emoticons/v1/1900/1.0"
  "RedCoat" : "https://static-cdn.jtvnw.net/emoticons/v1/22/1.0"
  "ResidentSleeper" : "https://static-cdn.jtvnw.net/emoticons/v1/245/1.0"
  "riPepperonis" : "https://static-cdn.jtvnw.net/emoticons/v1/62833/1.0"
  "RitzMitz" : "https://static-cdn.jtvnw.net/emoticons/v1/4338/1.0"
  "RuleFive" : "https://static-cdn.jtvnw.net/emoticons/v1/361/1.0"
  "SeemsGood" : "https://static-cdn.jtvnw.net/emoticons/v1/64138/1.0"
  "ShadyLulu" : "https://static-cdn.jtvnw.net/emoticons/v1/52492/1.0"
  "ShazBotstix" : "https://static-cdn.jtvnw.net/emoticons/v1/87/1.0"
  "ShibeZ" : "https://static-cdn.jtvnw.net/emoticons/v1/27903/1.0"
  "SmoocherZ" : "https://static-cdn.jtvnw.net/emoticons/v1/89945/1.0"
  "SMOrc" : "https://static-cdn.jtvnw.net/emoticons/v1/52/1.0"
  "SMSkull" : "https://static-cdn.jtvnw.net/emoticons/v1/51/1.0"
  "SoBayed" : "https://static-cdn.jtvnw.net/emoticons/v1/1906/1.0"
  "SoonerLater" : "https://static-cdn.jtvnw.net/emoticons/v1/355/1.0"
  "SriHead" : "https://static-cdn.jtvnw.net/emoticons/v1/14706/1.0"
  "SSSsss" : "https://static-cdn.jtvnw.net/emoticons/v1/46/1.0"
  "StinkyCheese" : "https://static-cdn.jtvnw.net/emoticons/v1/90076/1.0"
  "StoneLightning" : "https://static-cdn.jtvnw.net/emoticons/v1/17/1.0"
  "StrawBeary" : "https://static-cdn.jtvnw.net/emoticons/v1/37/1.0"
  "SuperVinlin" : "https://static-cdn.jtvnw.net/emoticons/v1/31/1.0"
  "SwiftRage" : "https://static-cdn.jtvnw.net/emoticons/v1/34/1.0"
  "TF2John" : "https://static-cdn.jtvnw.net/emoticons/v1/1899/1.0"
  "TheRinger" : "https://static-cdn.jtvnw.net/emoticons/v1/18/1.0"
  "TheTarFu" : "https://static-cdn.jtvnw.net/emoticons/v1/70/1.0"
  "TheThing" : "https://static-cdn.jtvnw.net/emoticons/v1/7427/1.0"
  "ThunBeast" : "https://static-cdn.jtvnw.net/emoticons/v1/1898/1.0"
  "TinyFace" : "https://static-cdn.jtvnw.net/emoticons/v1/67/1.0"
  "TooSpicy" : "https://static-cdn.jtvnw.net/emoticons/v1/359/1.0"
  "TriHard" : "https://static-cdn.jtvnw.net/emoticons/v1/171/1.0"
  "TTours" : "https://static-cdn.jtvnw.net/emoticons/v1/38436/1.0"
  "twitchRaid" : "https://static-cdn.jtvnw.net/emoticons/v1/62836/1.0"
  "UleetBackup" : "https://static-cdn.jtvnw.net/emoticons/v1/49/1.0"
  "UncleNox" : "https://static-cdn.jtvnw.net/emoticons/v1/3666/1.0"
  "UnSane" : "https://static-cdn.jtvnw.net/emoticons/v1/71/1.0"
  "VaultBoy" : "https://static-cdn.jtvnw.net/emoticons/v1/54090/1.0"
  "VoHiYo" : "https://static-cdn.jtvnw.net/emoticons/v1/81274/1.0"
  "Volcania" : "https://static-cdn.jtvnw.net/emoticons/v1/166/1.0"
  "WholeWheat" : "https://static-cdn.jtvnw.net/emoticons/v1/1896/1.0"
  "WinWaker" : "https://static-cdn.jtvnw.net/emoticons/v1/167/1.0"
  "WTRuck" : "https://static-cdn.jtvnw.net/emoticons/v1/1897/1.0"
  "WutFace" : "https://static-cdn.jtvnw.net/emoticons/v1/28087/1.0"
  "YouWHY" : "https://static-cdn.jtvnw.net/emoticons/v1/4337/1.0"
  "MangoForty" : "https://static-cdn.jtvnw.net/emoticons/v1/28700/1.0"
  "MangoBANGER" : "https://static-cdn.jtvnw.net/emoticons/v1/28701/1.0"
  "MangoBaby" : "https://static-cdn.jtvnw.net/emoticons/v1/15163/1.0"
  "MangoCloud9" : "https://static-cdn.jtvnw.net/emoticons/v1/15164/1.0"
  "MangoFox" : "https://static-cdn.jtvnw.net/emoticons/v1/15165/1.0"
  "MangoFalco" : "https://static-cdn.jtvnw.net/emoticons/v1/15166/1.0"
  "MangoAT" : "https://static-cdn.jtvnw.net/emoticons/v1/20386/1.0"
  "MangoUSA" : "https://static-cdn.jtvnw.net/emoticons/v1/20387/1.0"
  "MangoChamp" : "https://static-cdn.jtvnw.net/emoticons/v1/24983/1.0"
  "MangoScorp" : "https://static-cdn.jtvnw.net/emoticons/v1/24984/1.0"
  "MangoPog" : "https://static-cdn.jtvnw.net/emoticons/v1/81426/1.0"
  "MangoBUSTER" : "https://static-cdn.jtvnw.net/emoticons/v1/36469/1.0"
  "Mango19" : "https://static-cdn.jtvnw.net/emoticons/v1/36468/1.0"
  "MangoAWP" : "https://static-cdn.jtvnw.net/emoticons/v1/39793/1.0"
  "MangoW" : "https://static-cdn.jtvnw.net/emoticons/v1/88281/1.0"
  "MangoBat" : "https://static-cdn.jtvnw.net/emoticons/v1/46282/1.0"
  "MangoKrey" : "https://static-cdn.jtvnw.net/emoticons/v1/45241/1.0"
  "MangoWiener" : "https://static-cdn.jtvnw.net/emoticons/v1/49150/1.0"
  "MangoHamburgers" : "https://static-cdn.jtvnw.net/emoticons/v1/49346/1.0"
  "MangoANGLE" : "https://static-cdn.jtvnw.net/emoticons/v1/61817/1.0"
  "MangoAwCrud" : "https://static-cdn.jtvnw.net/emoticons/v1/70602/1.0"
  "MangoNeo" : "https://static-cdn.jtvnw.net/emoticons/v1/84600/1.0"
  "MangoRIP" : "https://static-cdn.jtvnw.net/emoticons/v1/85173/1.0"
  "MangoL8R" : "https://static-cdn.jtvnw.net/emoticons/v1/87498/1.0"
  "MangoDOWN" : "https://static-cdn.jtvnw.net/emoticons/v1/89561/1.0"
ourEmoticons =
  "Halk": "http://smileys.emoticonsonly.com/emoticons/h/hawk-81.gif"
  "KDGI": "http://www.emotiyou.com/galerie/tv/dessins-animes/bob-eponge/bob/201109041811HBR.gif"
  "SloshedJon" : "http://i.imgur.com/AZK1PNX.png"
  "FattyFedora" : "http://i.imgur.com/jZa8JGR.png"
  "SadKeith" : "http://i.imgur.com/6Ji3SUv.png"
  "SadJonjo" : "http://i.imgur.com/YYvMFmU.png"
  "ShittersClogged" : "http://i.imgur.com/mawXVw5.png"
  "RipKeith" : "http://i.imgur.com/JEb2zrl.png"
  "BanePostCia" : "http://i.imgur.com/TxZfAFh.png"
  "BanePostBane" : "http://i.imgur.com/2tP8nq2.png" # 6 shields applied as of 2017
  "GoodShit" : "https://i.imgur.com/i1rF9Mg.png"
  "DankMemes" : "http://i.imgur.com/TKbLBWy.png"
  "DankestMemes" : "http://i.imgur.com/bXTDR2r.png"
  "200%Mad" : "http://i.imgur.com/DuxEKjJ.png"
  "HonHon" : "http://i.imgur.com/onAKPvF.png"
  "CartoonKeith" : "http://i.imgur.com/fej5DLu.png"
  "WewLad" : "http://i.imgur.com/QeqJ28J.png"
  "VideoTapes" : "http://i.imgur.com/bVwmh9q.gif"
  "DootDoot" : "http://www.netanimations.net/Moving-picture-skull-playing-coronet-animation.gif"
  "SickSpins" : "http://i.imgur.com/BTOckJP.gif"
  "OhYou" : "http://i.imgur.com/nvBbE.gif"
  "Gib": "http://i.imgur.com/YYfXLjz.gif"
  "BatemanDubs": "http://i.imgur.com/BkGdKTY.png"
  "KevinPostKevin": "http://i.imgur.com/QsiJIVb.png"
  "RipJon": "http://i.imgur.com/E486QSD.png"
  "RipHenry": "http://i.imgur.com/OfwXCob.png"
  "CrazyKeith": "http://i.imgur.com/JEb2zrl.png"
  "2Spooky": "https://media.giphy.com/media/NT7rUTkLZqQPS/giphy.gif"
  "GreyJon": "http://i.imgur.com/OiCxjHS.png"
  "GrayJon": "http://i.imgur.com/OiCxjHS.png"
  "ZenJon": "http://i.imgur.com/K8rQ0Tk.png"
  "EvansLaugh": "http://i.imgur.com/S3hikEq.png"
  "StrongPotions": "http://i.imgur.com/BloUFZi.png"
  "PotionSeller": "http://i.imgur.com/J9NxZQ4.png"
  "LilJon":"http://i.imgur.com/T0GWs3A.png"
  "ThatsBait":"http://i.imgur.com/N5iUOJa.png"
  "PhilBam": "http://i.imgur.com/IjD6FZi.gif"
  "AmericanRip": "http://i.imgur.com/YRq5HRN.png"
  "666Trips": "http://i.imgur.com/wksDj8i.jpg"
  "MeatRub": "http://img15.deviantart.net/df15/i/2012/237/a/a/gotta_go_fast_by_whiie_z-d5cdoq5.png"
  "4Scoops": "http://i.imgur.com/4AMeQP1.png"
  "BillHitchert": "http://i.imgur.com/5qeuUE7.png"
  "Atodaso": "http://imgur.com/ymH0NVl.png"
  "CmonNow": "http://i.imgur.com/bk7U205.png"
  "JonjoGF": "http://imgur.com/C0IepFR.png"
  "Pepe": "http://i.imgur.com/lG268lj.png"
  "HappyKeith": "http://i.imgur.com/P2F6JuD.png"
  "Cool": "http://i.imgur.com/8mt5E7C.png"
  "ThisIsBait": "http://i.imgur.com/KpvfDHo.png"
  "FacePalm": "http://i.imgur.com/cEkA9zI.png"
  "Gottem": "http://i.imgur.com/9JohgrD.png"
  "Gottum": "http://i.imgur.com/9JohgrD.png"
  "ThisIsFine": "http://imgur.com/fTe3YMx.gif"
  "Tanks": "http://i.imgur.com/XE9zBT8.png"
  "TryNotToCry": "http://imgur.com/LVEnuMe.gif"
  "Hmmm": "http://imgur.com/tzCrrch.png"
  "yeha": "http://i.imgur.com/DySsYTG.png"
  "Yeha": "http://i.imgur.com/DySsYTG.png"
  "HenryGunHenry": "http://imgur.com/km9r1Pp.png"
  "GrayHon": "http://i.imgur.com/RTsL5co.png"
  "GreyHon": "http://i.imgur.com/RTsL5co.png"
  "JustFuckMyShitUp": "http://i.imgur.com/m0twmSj.png"
  "DrEvil": "http://i.imgur.com/vwsVEIr.png"
  "ForgetPast": "http://wiki.dfo-world.com/images/c/c4/BottomsUpAni.gif"
  "CrashDance": "http://i.imgur.com/L9JsSdw.gif"
  "HMMM": "http://imgur.com/HzhlCPK.png"
  "Goteem": "http://i.imgur.com/V0jH3HG.png"
  "GotEem": "http://i.imgur.com/V0jH3HG.png"
  "Humanity": "http://i.imgur.com/7Sh9H13.png"
  "tpWhite": "http://i.imgur.com/3nqrrth.png"
  "tpBLBLBL": "http://i.imgur.com/HXB8MLJ.png"
  "tpGG": "http://i.imgur.com/ZqgXfBK.png"
  "tpFX1": "http://i.imgur.com/LxxSL8o.png"
  "tpAIYIYI": "http://i.imgur.com/h7acPhf.png"
  "tpAYAY": "http://i.imgur.com/h7acPhf.png"
  "MorphinTime": "http://i.imgur.com/HXB8MLJ.png"
  "tpFree": "http://i.imgur.com/eVq6f6X.png"
  "tpBlue": "http://i.imgur.com/ZqgXfBK.png"
  "tpYellow": "http://i.imgur.com/JaHoijB.png"
  "tpRed": "http://i.imgur.com/WyxioZv.png"
  "tpPink": "http://i.imgur.com/Q3Kl2j6.png"
  "tpBlack": "http://i.imgur.com/bjMlP03.png"
  "tpGreen": "http://i.imgur.com/m0XlGmG.png"
  "tpHeresTommy": "http://i.imgur.com/bSQJb1w.png"
  "WitherJonWither": "http://i.imgur.com/hHzI8pj.gif"
  "JonjoWitherJonjo": "http://i.imgur.com/hHzI8pj.gif"
  "PeHenryPe": "http://imgur.com/q6ANjU4.png"
  "HappyLark": "http://imgur.com/Rc0ooTm.png"
  "WellMemed": "http://imgur.com/wZQoCDq.png"
  "Interdasting": "http://i.imgur.com/vg3TLNk.png"
  "Bretonnia": "http://i.imgur.com/hfwJRFW.png"
  "WinkJon": "http://imgur.com/kZn71iY.gif"
  "INTERDASTING": "http://imgur.com/38xrKvJ.png"
  "DERKISFINE": "http://imgur.com/Jk6wVxf.gif"
  "DerkIsFine": "http://imgur.com/LcS3JMn.png"
  "AnimeKeith": "http://imgur.com/dUOfnNV.gif"
  "ScoffJon": "http://imgur.com/qSJN4zh.gif"
  "Aeh": "http://imgur.com/bOxhqMy.png"
  "SadPingu": "http://imgur.com/uXc0Ufz.png"
  "DudeJon": "http://i.imgur.com/WyPa011.png"
  "SoDusted": "http://i.imgur.com/JHors09.png"
  "RingBear": "https://m.popkey.co/157257/rzrbW.gif"
  "\\:\\)\\<3": "http://i.imgur.com/SWD6uJ5.png"
  "SexyJon": "http://i.imgur.com/aztH9e7.png"
  "HenryBlazeHenry": "http://i.imgur.com/OWrIo27.png"
  "HenrySuccHenry": "http://i.imgur.com/g5uMi22.png"
  "Rickyism": "http://i.imgur.com/rim97Om.png"
  "Fug": "http://i.imgur.com/KkdXvZW.png"
  "PalmJo": "http://i.imgur.com/HzzHOP1.png"
  "ThrashHon": "http://i.imgur.com/ky2clQx.gif"
  "Yee": "http://i.imgur.com/V1gcXUQ.png"
  "Derek": "https://i.imgur.com/iDNM4pZ.jpg"
  "Derk": "https://i.imgur.com/iDNM4pZ.jpg"
  "HypeWizardHype": "https://i.imgur.com/RQGMdFS.gif"
  "Franklin": "https://i.imgur.com/FmRkYEZ.png"
  "Michael": "https://i.imgur.com/GbkyHDg.png"
  "Zero": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-zero_30-fe0f-20e3.png"
  "One": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-one_31-fe0f-20e3.png"
  "Two": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-two_32-fe0f-20e3.png"
  "Three": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-three_33-fe0f-20e3.png"
  "Four": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-four_34-fe0f-20e3.png"
  "Five": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-five_35-fe0f-20e3.png"
  "Six": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-six_36-fe0f-20e3.png"
  "Seven": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-seven_37-fe0f-20e3.png"
  "Eight": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-eight_38-fe0f-20e3.png"
  "Nine": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-digit-nine_39-fe0f-20e3.png"
  "Ten": "https://emojipedia-us.s3.amazonaws.com/thumbs/72/facebook/111/keycap-ten_1f51f.png"
  "WojackCry": "https://i.imgur.com/Hq9Bw02.png"
  ":D": "https://i.imgur.com/cS6so1h.png"
  "KeithDabKeith": "https://i.imgur.com/iDdiMjK.png"
textEmoticons =
  "Denko": "(´・ω・｀)"
  "Lenny": "( ͡° ͜ʖ ͡°)"
roboEmoticons =
  "MiniDerek" : "http://i.imgur.com/d1l7yQK.png"
  "MiniHonry" : "http://i.imgur.com/dHdWrqj.png"
  "MiniJonjo" : "http://i.imgur.com/fCYpvbZ.png"
  "MiniKeith" : "http://i.imgur.com/qCxBqa5.png"

emoticons = {}
Object.assign(emoticons, twitchEmoticons)
Object.assign(emoticons, ourEmoticons)
Object.assign(emoticons, roboEmoticons)

purgeRegex = new RegExp("Purge", 'g')
purgeEmoticon = "<img src=\"http://imgur.com/VbXDnsr.png\" border=\"0\" text-align=\"center !important\" height=\"2000px\" alt=\"Purge\" title=\"Purge emoticon\" style=\"image-rendering: pixelated;\"/>"

genEmoticon = (key, big) ->
  if big
    "<img src=\"#{emoticons[key]}\" border=\"0\" text-align=\"center !important\" height=\"150\" alt=\"#{key}\" title=\"#{key} emoticon\" style=\"image-rendering: pixelated;\"/>"
  else
    "<img src=\"#{emoticons[key]}\" border=\"0\" height=\"35\" alt=\"#{key}\" title=\"#{key} emoticon\"/>"
export default
  replace: (text, id, author, big) ->
    if (purgeRegex.test(text) and big)
      text = text.replace(purgeRegex, purgeEmoticon)
    else
      if big and author == localStorage.displayName
        for key, value of roboEmoticons
          regex = new RegExp(key, 'g')
          if regex.test(text)
            author = text.substring(4)
            markov(author, id)
            return "#{genEmoticon(key, false)} is thinking..."
      for key, value of textEmoticons
        regex = new RegExp(key, 'g')
        text = text.replace(regex, value)
      for key, link of emoticons
        regex = new RegExp(key, 'g')
        if big
          text = text.replace(regex, genEmoticon(key, big))
        else
          text = text.replace(regex, genEmoticon(key, big))
      text
  singleEmoticon: (text) ->
    if purgeRegex.test(text) and text.replace(purgeRegex, ' ').length == 1
      return true
    for key, link of emoticons
      regex = new RegExp(key, 'g')
      if regex.test(text) and text.replace(regex, ' ').length == 1
        return true
    false
  ourEmoticons: ourEmoticons
  twitchEmoticons: twitchEmoticons
  textEmoticons: textEmoticons
  emoticons: emoticons
  genEmoticon: genEmoticon
